project_name: prometheus-libvirt-exporter
before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: prometheus-libvirt-exporter
    dir: .
    main: ./libvirt_exporter.go
    binary: prometheus-libvirt-exporter
    flags:
      - -tags=netgo
      - -v
      - -a
    ldflags:
      - -w -s
      - -X main.version=v{{ .Version }} -X main.commit={{ .Commit }}
    goos:
      - linux
    goarch:
      - amd64

dockers:
  - ids:
      - prometheus-libvirt-exporter
    image_templates:
      - kiennt26/{{ .ProjectName }}:v{{ .Version }}-amd64
    goos: linux
    goarch: amd64
    dockerfile: goreleaser.dockerfile
    build_flag_templates:
      - "--build-arg=BINARY_NAME={{ .ProjectName }}"
      - "--platform=linux/amd64"
    use: buildx

docker_manifests:
- name_template: 'kiennt26/{{ .ProjectName }}:{{ .Version }}'
  image_templates:
  - 'kiennt26/{{ .ProjectName }}:v{{ .Version }}-amd64'

#Configuration for building packages for apk, deb and rpm package managers
nfpms:
  - id: "prometheus-libvirt-exporter"
    package_name: "prometheus-libvirt-exporter"
    file_name_template: prometheus-libvirt-exporter-{{ .Version }}.{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}
    builds:
      - prometheus-libvirt-exporter
    maintainer: "kiennt26"
    description: |
      Prometheus-libvirt-exporter service (host and vm metrics exposed for prometheus, written in Go with pluggable metric collectors)
    homepage: "https://github.com/ntk148v/libvirt-exporter"
    license: "MIT License"
    formats:
      - deb
      - rpm
    bindir: "/usr/bin"
    priority: optional
    contents:
      - src: contrib/prometheus-libvirt-exporter.service
        dst: /etc/systemd/system/prometheus-libvirt-exporter.service

archives:
  - name_template: "{{ .ProjectName }}-{{ .Version }}.{{ .Os }}-{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}"
    format: tar.gz
    wrap_in_directory: true

checksum:
  name_template: "{{ .ProjectName }}-{{ .Version }}_checksums.txt"
  algorithm: sha256

# Configuration for GitHub Releases
release:
  github:
    owner: ntk148v
    name: libvirt-exporter
  footer: |
    ## Docker Images
    - kiennt26/prometheus-libvirt-exporter:{{ .Tag }} (universal, multi-platform)
    - kiennt26/prometheus-libvirt-exporter:{{ .Tag }}-amd64
  prerelease: auto
  replace_existing_draft: true
